### ISSUE TITLE
'get_comms_doc_info' should return lesson material url 

### ISSUE THREAD

**Issue by svenvanderburg** [esciencecenter-digital-skills/training-infrastructure#29]
In order to solve https://github.com/esciencecenter-digital-skills/template-docs-coordination/issues/4, we need `get_comms_doc_info` to return also the lesson material url (i.e. https://carpentries-incubator.github.io/deep-learning-intro/). Not that this is not the lesson material github repo, but the actual github pages that belong to it.

**Comment by bvreede** [comment]
The actual URL seems to be an error with the workshop metadata: `get_comms_doc_info` simply returns the link that was written in the workshop metadata repository, so if links are referred to the github repo instead of the web page, this needs to be fixed per curriculum.

The broken syntax in the comms doc was due to a problem in the template. It has been fixed [here](https://github.com/esciencecenter-digital-skills/template-docs-coordination/commit/14a5586a374a336e03227c3f016339151b136aef) and [here](https://github.com/esciencecenter-digital-skills/template-docs-coordination/commit/3a116ae81ddae60d2cd6f044942fb94c3a74d370).
