### ISSUE TITLE
Error message when a workshop location is not found

### ISSUE THREAD

**Issue by bvreede** [esciencecenter-digital-skills/training-infrastructure#30]
When unclear alternative locations to the eScience Center address (e.g.: `WDCC, WUR, Wageningen`) are given as a workshop address, the error message when running `get_future_workshops()` is:

```
No results for query WDCC, WUR, Wageningen
```

@liekelotte @svenvanderburg  is it necessary that this query is successful? (Given how often we teach external workshops...)

If so: it would be good to have a better error message that tells the user e.g. to update the Holy Excel Sheet and run the workflow again.

**Comment by svenvanderburg** [comment]
@bvreede we teach quite a few external workshops each year (let's say 5) so it would be nice if the training infrastructure accommodates for it. 

It is not clear to me why this results in an error and what are the consequences (I guess no communication, debrief, planning documents are created, which is bad). 'update the Holy Excel Sheet and run the workflow again' would not be a much better error message, because I wouldn't know how to update the Holy Excel Sheet.

:)

**Comment by bvreede** [comment]
Thanks @svenvanderburg, that is good to know. I think the effect is that the exact GPS location is not added, which is not disastrous but also not good; if anything it should not happen silently.

The Holy Excel Sheet is the sharepoint file that contains all workshop information, sorry for the lingo 😅 — it's @liekelotte's pet name for the thing.

**Comment by svenvanderburg** [comment]
I know what the Holy Excel Sheet is and I worship it even more than Lieke did. I just wouldn't know how to update it so that the workshop location is read out correctly ;) (Which is still not clear to me)

**Comment by bvreede** [comment]
Aha 😅 sorry for misunderstanding.

Yes, this is a good point. I think OSM would need a physical address, and not just `WDCC, WUR, Wageningen` (or `Netherlands eScience Center`, for that matter) to be able to generate coordinates. This is useful to put into the error message, as well as the exact column that needs to be adjusted.
